### ISSUE TITLE
Openstack extension for Newton

### ISSUE THREAD

**Issue by ge0rgi** [opencit/opencit-openstack-extensions#1]
Hello

I am currently studying Computer Science Master. Originally I was supposed to use OpenAttestation and OpenStack in my master thesis and make some enhancements. However, yesterday I found out that OpenAttestation is no longer developed and is superseded by OpenCIT. I am thinking about using OpenCIT instead of OpenAttestation, however as far as I understand there is currently no OpenCIT extension for Newton. Are there any plans for supporting Newton or is somebody working on this? If not I could talk to my supervisor and potentially alter my topic to make an extension for Newton.

Regards
Georgi

**Comment by ZahediAquino** [comment]
We are planning support for Newton in 2017, no specific date yet.
